#   A basic travis.yml boilerplate for Django projects



language: python



python:
  
  - 3.7

services: 

  - sqlite

env:

  - DJANGO=2.1.4 DB=sqlite

before_install:

  - cd SemStew

install:

  - python setup.py install
  - python manage.py migrate

before_script:

  - cd SemStew

script:

  - python manage.py syncdb --noinput
  - python manage.py test