#   A basic travis.yml boilerplate for Django projects



language: python



python:
  - 3.5

  - 3.6
  
  - 3.7



services: 

  - sqlite

env:

  - DJANGO=2.1.4 DB=sqlite



before_install:

  - python SemStew\manage.py migrate


install:

  - .\SemStew\setup.py install



before_script:

  #something



script:

  - python manage.py syncdb --noinput