# Generated by Django 2.1.2 on 2018-11-01 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('semstew', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AboutUsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=128)),
                ('description_text', models.CharField(max_length=128)),
                ('fotogallery_text', models.CharField(max_length=128)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semstew.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AllergenName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semstew.Allergen')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semstew.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=512)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('description', models.TextField(blank=True)),
                ('opening_hours', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='semstew.Category')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semstew.Category')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semstew.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=128)),
                ('description_text', models.CharField(max_length=128)),
                ('image_map', models.ImageField(upload_to='')),
                ('image_restaurant', models.ImageField(upload_to='')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semstew.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=256)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('mail', models.CharField(blank=True, max_length=256)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semstew.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IntroConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=128)),
                ('introduction_text', models.CharField(max_length=128)),
                ('news_text', models.CharField(max_length=128)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semstew.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('amount', models.IntegerField()),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='semstew.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ItemAllergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semstew.Allergen')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semstew.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semstew.Item')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semstew.Language')),
            ],
        ),
        migrations.CreateModel(
            name='MainPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semstew.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semstew.Item')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semstew.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='MenuName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semstew.Language')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semstew.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='NewName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semstew.Language')),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semstew.New')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('person', models.CharField(max_length=256)),
                ('address', models.TextField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semstew.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semstew.Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semstew.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('person', models.CharField(max_length=256)),
                ('table', models.IntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semstew.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=128)),
                ('table_number_text', models.CharField(max_length=256)),
                ('time_from_text', models.CharField(max_length=256)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semstew.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('ico', models.IntegerField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UnitName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semstew.Language')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semstew.Unit')),
            ],
        ),
        migrations.AddField(
            model_name='newname',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semstew.Restaurant'),
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semstew.Unit'),
        ),
        migrations.AddField(
            model_name='intro',
            name='intro_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semstew.IntroConfig'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semstew.ContactConfig'),
        ),
        migrations.AddField(
            model_name='branch',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semstew.Restaurant', unique=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='aboutus_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semstew.AboutUsConfig'),
        ),
    ]
