# Generated by Django 2.1.2 on 2018-11-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semstew', '0003_auto_20181101_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactconfig',
            name='image_map',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='contactconfig',
            name='image_restaurant',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mainpictures',
            name='image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
