# Generated by Django 2.1.2 on 2018-11-01 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semstew', '0004_auto_20181101_1411'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='allergenname',
            unique_together={('allergen', 'language')},
        ),
    ]
