# Generated by Django 2.1.4 on 2018-12-28 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semstew', '0007_new_restaurant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='restaurant_id',
        ),
    ]
