# Generated by Django 2.1.4 on 2018-12-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semstew', '0008_remove_new_restaurant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.FloatField(),
        ),
    ]
