# Generated by Django 2.1.4 on 2018-12-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semstew', '0010_auto_20181228_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactconfig',
            name='image_map',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contactconfig',
            name='image_restaurant',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
