# Generated by Django 2.1.5 on 2019-02-10 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semstew', '0011_auto_20181228_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactconfig',
            old_name='language',
            new_name='lang',
        ),
    ]
