# Generated by Django 2.1.5 on 2019-02-10 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semstew', '0012_auto_20190210_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactconfig',
            old_name='lang',
            new_name='language',
        ),
    ]
