# Generated by Django 2.1.5 on 2019-02-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semstew', '0013_auto_20190210_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='header',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
