# Generated by Django 2.1.5 on 2019-02-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semstew', '0016_remove_orderconfig_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconfig',
            name='header_more',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
